### ISSUE TITLE
test

### ISSUE THREAD

**Issue by JasonHorkles** [JasonHorkles/EntityClearer#2]
### Description of the bug

test

### Steps to reproduce the problem

test

### Expected behavior

yes

### Output of `/version`

This server is running Tuinity version git-Tuinity-"b12d0cc" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Tuinity-"d5261ad" (MC: 1.16.5)

### Output of `/version EntityClearer`

![image](https://user-images.githubusercontent.com/51760372/116762026-6eaf2680-a9d6-11eb-96fc-37521e31f17d.png)

### EntityClearer config.yml

```yaml
# This plugin uses bStats metrics
# https://bstats.org/plugin/bukkit/EntityClearer/10915
# Metrics can be disabled in the bStats config.yml

# Interval in minutes the clear task should run
interval: 15

# The sound to play when showing the warnings
# See https://minecraft.fandom.com/wiki/Sounds.json#Java_Edition_values for all sounds
# Set to '' for no sound
sound: 'ui.button.click'

# The entities to clear from the world
# See https://papermc.io/javadocs/paper/1.16/org/bukkit/entity/EntityType.html for all entities
entities:
  - ZOMBIE
  - SKELETON
  - CREEPER
  - SPIDER
  - BLAZE
  - CAVE_SPIDER
  - CHICKEN
  - ENDERMAN
  - SHEEP
  - GUARDIAN
  - ZOMBIFIED_PIGLIN
  - SQUID
  - WOLF
  - CAT
  - MINECART
  - ARMOR_STAND
  - BEE

spawn-reason:
  # Should only entities with a specific spawn reason be removed?
  # Setting this to false will check for any spawn reason
  enabled: false
  # See https://papermc.io/javadocs/paper/1.16/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html for all spawn reasons
  reasons:
    - SPAWNER
    - SPAWNER_EGG
    - DISPENSE_EGG

nearby-entities:
  # Should the plugin only remove entities that have multiple entities nearby?
  # This is useful to only remove large groups of animals while keeping alone entities alive
  # Using this would prevent every entity from being removed then just respawning again naturally
  enabled: true
  # The distance in blocks that the plugin should check for extra entities
  x: 5
  y: 3
  z: 5
  # How many additional entities must be around the first entity to be removed?
  count: 4

# The worlds to check and remove entities from
worlds:
  - main
  - main_nether
  - main_the_end
  - plot
  - utility

# Should using the command /clearentities start the countdown or instantly remove the entities?
countdown-on-command: false

# Should named entities be removed?
remove-named: false

messages:
  # Should there be action bar messages?
  actionbar: true
  # Should there be chat messages?
  chat: false
  # Should the messages still show if the amount of removed entities will be 0?
  show-if-zero: false
  actionbar-message: "&x&f&f&9&b&0&f&lCommon entities will be removed in &e&l{SECONDS} &x&f&f&9&b&0&f&lsecond{S}!"
  actionbar-completed-message: "&x&f&f&9&b&0&f&lRemoved &e&l{ENTITIES} &x&f&f&9&b&0&f&lentities!"
  chat-message: "&cCommon entities will be removed in &7{SECONDS} &csecond{S}!"
  chat-completed-message: "&cRemoved &7{ENTITIES} &centities!"

# When should the warning messages send?
# Time is in seconds remaining before the clear task
warning-messages:
  60-seconds: false
  45-seconds: false
  30-seconds: true
  15-seconds: false
  5-seconds: true
  4-seconds: true
  3-seconds: true
  2-seconds: true
  1-second: true

low-tps:
  # Should the entity removal task be triggered when the TPS is low?
  # This feature requires Paper (https://papermc.io/)
  enabled: true
  # Below what TPS should the plugin remove the entities?
  threshold: 17
  # Should the plugin remove the entities instantly or trigger the countdown?
  # Warning: If the TPS is too low and remove-instantly is false, the plugin may
  # not be able to remove the entities before the server crashes
  remove-instantly: true
  # Should there be a chat message sent to players with the `entityclearer.lowtps`
  # permission stating that the TPS is low?
  chat: true
  chat-message: "&c&lWarning: TPS low &8&l(&7&l{TPS}&8&l)&c&l! Removing entities..."
```
